# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
#!/bin/bash

set -e

function merge_dirs() {
    local SRC="$1"
    local DST="$2"

    if [[ -L "$SRC" ]]; then
        return 0
    fi

    if ls "$SRC"/*; then
        cp -rf "$SRC/"* "$DST/"
    fi
    rm -rf "$SRC"
    ln -s "$DST" "$SRC"
}

merge_dirs /usr/local/include /usr/include
merge_dirs /usr/local/lib /usr/lib

apt-get update
apt-get install -y git python-pip python-dev libgsl0-dev \
    vim python-numpy python-scipy python-matplotlib libicu52 mayavi2
ln -s /usr/include/gsl /usr/local/include/gsl
pip install numpy
git clone https://github.com/apetri/LensTools

cd LensTools
python setup.py build
python setup.py install
chown vagrant -R .
chgrp vagrant -R .
cd ..

SCRIPT

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provision "shell", inline: $script
end
