# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
#!/bin/bash

apt-get update
apt-get install -y git python-pip python-dev libgsl0-dev \
    vim python-numpy python-scipy python-matplotlib libicu52 mayavi2
ln -s /usr/include/gsl /usr/local/include/gsl
pip install numpy
git clone https://github.com/apetri/LensTools

cd LensTools
python setup.py build
python setup.py install
chown vagrant -R .
chgrp vagrant -R .
cd ..

SCRIPT

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provision "shell", inline: $script
end
